# Generated by Django 2.1.2 on 2018-11-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('artist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('name', models.TextField()),
                ('lyric', models.TextField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmusic.Album')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key='true', serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='singer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmusic.Song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmusic.User'),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playmusic.User'),
        ),
    ]
